### ISSUE TITLE
Angular 17 Support

### ISSUE THREAD

**Issue by swati-malhotra** [gdgvda/ngx-bootstrap-icons-picker#1]
Hi Team,

Can you add angular 17 support. Currently with Angular 17 its failing to install.

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: platform-frontend@0.0.0
> npm ERR! Found: @angular/common@17.0.8
> npm ERR! node_modules/@angular/common
> npm ERR!   @angular/common@"^17.0.6" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer @angular/common@"^14.2.0" from ngx-bootstrap-icons-picker@1.0.8
> npm ERR! node_modules/ngx-bootstrap-icons-picker
> npm ERR!   ngx-bootstrap-icons-picker@"1.0.8" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by Zavy86** [comment]
working on it

https://github.com/gdgvda/ngx-bootstrap-icons-picker/tree/angular-17

**Comment by swati-malhotra** [comment]
Can you please update other dependencies with it?

Like, ngbootstrap, bootstrap, bootstrap-icons.

**Comment by Zavy86** [comment]
yes i will update all to the latest available

**Comment by Zavy86** [comment]
Hi @swati-malhotra, can you try please?

https://github.com/gdgvda/ngx-bootstrap-icons-picker/releases/tag/17.0.3
https://www.npmjs.com/package/ngx-bootstrap-icons-picker
